// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/timelineapi/timeline.proto

/*
Package timelineapi is a generated protocol buffer package.

It is generated from these files:
	pkg/timelineapi/timeline.proto

It has these top-level messages:
	GetRequest
	GetResponse
	Event
	EntitySummary
	EntryMetadata
	TimeRange
*/
package timelineapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import api "github.com/drausin/libri/libri/librarian/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	UserId    string     `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	TimeRange *TimeRange `protobuf:"bytes,2,opt,name=time_range,json=timeRange" json:"time_range,omitempty"`
	Limit     uint32     `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetRequest) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *GetRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetResponse struct {
	Events []*Event `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Time          int64          `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Author        *EntitySummary `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Reader        *EntitySummary `protobuf:"bytes,3,opt,name=reader" json:"reader,omitempty"`
	Envelope      *api.Envelope  `protobuf:"bytes,4,opt,name=envelope" json:"envelope,omitempty"`
	EntryMetadata *EntryMetadata `protobuf:"bytes,5,opt,name=entry_metadata,json=entryMetadata" json:"entry_metadata,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Event) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetAuthor() *EntitySummary {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Event) GetReader() *EntitySummary {
	if m != nil {
		return m.Reader
	}
	return nil
}

func (m *Event) GetEnvelope() *api.Envelope {
	if m != nil {
		return m.Envelope
	}
	return nil
}

func (m *Event) GetEntryMetadata() *EntryMetadata {
	if m != nil {
		return m.EntryMetadata
	}
	return nil
}

type EntitySummary struct {
	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *EntitySummary) Reset()                    { *m = EntitySummary{} }
func (m *EntitySummary) String() string            { return proto.CompactTextString(m) }
func (*EntitySummary) ProtoMessage()               {}
func (*EntitySummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EntitySummary) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *EntitySummary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EntitySummary) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type EntryMetadata struct {
	CreatedTime           uint32 `protobuf:"varint,1,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	MetadataCiphertext    []byte `protobuf:"bytes,2,opt,name=metadata_ciphertext,json=metadataCiphertext,proto3" json:"metadata_ciphertext,omitempty"`
	MetadataCiphertextMac []byte `protobuf:"bytes,3,opt,name=metadata_ciphertext_mac,json=metadataCiphertextMac,proto3" json:"metadata_ciphertext_mac,omitempty"`
}

func (m *EntryMetadata) Reset()                    { *m = EntryMetadata{} }
func (m *EntryMetadata) String() string            { return proto.CompactTextString(m) }
func (*EntryMetadata) ProtoMessage()               {}
func (*EntryMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EntryMetadata) GetCreatedTime() uint32 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *EntryMetadata) GetMetadataCiphertext() []byte {
	if m != nil {
		return m.MetadataCiphertext
	}
	return nil
}

func (m *EntryMetadata) GetMetadataCiphertextMac() []byte {
	if m != nil {
		return m.MetadataCiphertextMac
	}
	return nil
}

// TimeRange represents a [lower, upper) time range. Each bound is represented as microseconds
// since epoch. A zero-valued lower bound represents -Inf, and a zero-valued upper bound represents
// +Inf.
type TimeRange struct {
	LowerBound int64 `protobuf:"varint,1,opt,name=lower_bound,json=lowerBound" json:"lower_bound,omitempty"`
	UpperBound int64 `protobuf:"varint,2,opt,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
}

func (m *TimeRange) Reset()                    { *m = TimeRange{} }
func (m *TimeRange) String() string            { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()               {}
func (*TimeRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TimeRange) GetLowerBound() int64 {
	if m != nil {
		return m.LowerBound
	}
	return 0
}

func (m *TimeRange) GetUpperBound() int64 {
	if m != nil {
		return m.UpperBound
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "timelineapi.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "timelineapi.GetResponse")
	proto.RegisterType((*Event)(nil), "timelineapi.Event")
	proto.RegisterType((*EntitySummary)(nil), "timelineapi.EntitySummary")
	proto.RegisterType((*EntryMetadata)(nil), "timelineapi.EntryMetadata")
	proto.RegisterType((*TimeRange)(nil), "timelineapi.TimeRange")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Timeline service

type TimelineClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type timelineClient struct {
	cc *grpc.ClientConn
}

func NewTimelineClient(cc *grpc.ClientConn) TimelineClient {
	return &timelineClient{cc}
}

func (c *timelineClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/timelineapi.Timeline/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Timeline service

type TimelineServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterTimelineServer(s *grpc.Server, srv TimelineServer) {
	s.RegisterService(&_Timeline_serviceDesc, srv)
}

func _Timeline_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimelineServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timelineapi.Timeline/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimelineServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Timeline_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timelineapi.Timeline",
	HandlerType: (*TimelineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Timeline_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/timelineapi/timeline.proto",
}

func init() { proto.RegisterFile("pkg/timelineapi/timeline.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0xdb, 0x6d, 0x69, 0x26, 0x2d, 0x87, 0xe1, 0xa3, 0x51, 0x91, 0xa0, 0xe4, 0x54, 0x38,
	0xb4, 0x52, 0x11, 0x48, 0x20, 0x2e, 0x80, 0x60, 0xb5, 0x87, 0x5e, 0x4c, 0xef, 0x91, 0x9b, 0x8c,
	0x5a, 0x8b, 0xd8, 0x09, 0x8e, 0xb3, 0x90, 0xdf, 0xc2, 0xaf, 0xe4, 0x1f, 0x20, 0x3b, 0x69, 0xda,
	0x6a, 0x57, 0xda, 0x4b, 0x34, 0x7e, 0xef, 0xcd, 0xcc, 0xcb, 0x8c, 0x0d, 0x2f, 0x8a, 0x9f, 0xbb,
	0xa5, 0x11, 0x92, 0x32, 0xa1, 0x88, 0x17, 0xa2, 0x8b, 0x17, 0x85, 0xce, 0x4d, 0x8e, 0xc1, 0x09,
	0x37, 0xfd, 0xb4, 0x13, 0x66, 0x5f, 0x6d, 0x17, 0x49, 0x2e, 0x97, 0xa9, 0xe6, 0x55, 0x29, 0xd4,
	0x32, 0x13, 0x5b, 0x2d, 0x4e, 0xbe, 0x5c, 0x0b, 0xae, 0x96, 0xb6, 0x52, 0x9a, 0x27, 0x95, 0x24,
	0x65, 0xca, 0xa6, 0x54, 0xa4, 0x01, 0xae, 0xc8, 0x30, 0xfa, 0x55, 0x51, 0x69, 0x70, 0x02, 0x0f,
	0xab, 0x92, 0x74, 0x2c, 0xd2, 0xd0, 0x9b, 0x79, 0x73, 0x9f, 0x0d, 0xec, 0xf1, 0x3a, 0xc5, 0x77,
	0x00, 0xb6, 0x67, 0xac, 0xb9, 0xda, 0x51, 0x78, 0x31, 0xf3, 0xe6, 0xc1, 0xea, 0xd9, 0xe2, 0xc4,
	0xc6, 0x62, 0x23, 0x24, 0x31, 0xcb, 0x32, 0xdf, 0x1c, 0x42, 0x7c, 0x02, 0xfd, 0x4c, 0x48, 0x61,
	0xc2, 0xde, 0xcc, 0x9b, 0x8f, 0x59, 0x73, 0x88, 0x3e, 0x40, 0xe0, 0x7a, 0x96, 0x45, 0xae, 0x4a,
	0xc2, 0x37, 0x30, 0xa0, 0x1b, 0x6b, 0x29, 0xf4, 0x66, 0xbd, 0x79, 0xb0, 0xc2, 0xb3, 0xba, 0xdf,
	0x2c, 0xc5, 0x5a, 0x45, 0xf4, 0xcf, 0x83, 0xbe, 0x43, 0x10, 0xe1, 0xd2, 0xca, 0x9c, 0xcf, 0x1e,
	0x73, 0x31, 0xae, 0x60, 0xc0, 0x2b, 0xb3, 0xcf, 0x75, 0xeb, 0x70, 0x7a, 0x5e, 0x49, 0x19, 0x61,
	0xea, 0x1f, 0x95, 0x94, 0x5c, 0xd7, 0xac, 0x55, 0xda, 0x1c, 0x4d, 0x3c, 0x25, 0xed, 0x3c, 0xde,
	0x93, 0xd3, 0x28, 0xf1, 0x35, 0x0c, 0x49, 0xdd, 0x50, 0x96, 0x17, 0x14, 0x5e, 0xba, 0xac, 0xf1,
	0xa2, 0x51, 0x37, 0x20, 0xeb, 0x68, 0xfc, 0x0c, 0x8f, 0x48, 0x19, 0x5d, 0xc7, 0x92, 0x0c, 0x4f,
	0xb9, 0xe1, 0x61, 0xff, 0xee, 0x36, 0xba, 0x5e, 0xb7, 0x0a, 0x36, 0xa6, 0xd3, 0x63, 0xb4, 0x81,
	0xf1, 0x99, 0x0d, 0x7c, 0x0e, 0x3e, 0x39, 0xe0, 0xb8, 0xa7, 0x61, 0x03, 0x5c, 0xa7, 0x76, 0x2e,
	0x8a, 0xcb, 0x66, 0x47, 0x3e, 0x73, 0xb1, 0x9b, 0x55, 0x5d, 0x90, 0xfb, 0x43, 0x9f, 0xb9, 0x38,
	0xfa, 0xeb, 0xb9, 0xb2, 0xc7, 0x3e, 0xf8, 0x0a, 0x46, 0x89, 0x26, 0x6e, 0x28, 0x8d, 0xbb, 0xc9,
	0x8e, 0x59, 0xd0, 0x62, 0x76, 0xbf, 0xb8, 0x84, 0xc7, 0x87, 0xff, 0x88, 0x13, 0x51, 0xec, 0x49,
	0x1b, 0xfa, 0x63, 0x5c, 0xaf, 0x11, 0xc3, 0x03, 0xf5, 0xb5, 0x63, 0xf0, 0x3d, 0x4c, 0xee, 0x48,
	0x88, 0x25, 0x4f, 0x9c, 0x99, 0x11, 0x7b, 0x7a, 0x3b, 0x69, 0xcd, 0x93, 0x68, 0x0d, 0x7e, 0x77,
	0xa1, 0xf0, 0x25, 0x04, 0x59, 0xfe, 0x9b, 0x74, 0xbc, 0xcd, 0x2b, 0x95, 0xb6, 0x1b, 0x07, 0x07,
	0x7d, 0xb1, 0x88, 0x15, 0x54, 0x45, 0xd1, 0x09, 0x2e, 0x1a, 0x81, 0x83, 0x9c, 0x60, 0xf5, 0x1d,
	0x86, 0x9b, 0x76, 0xdc, 0xf8, 0x11, 0x7a, 0x57, 0x64, 0x70, 0x72, 0xb6, 0x80, 0xe3, 0x1b, 0x98,
	0x86, 0xb7, 0x89, 0xe6, 0xa2, 0x46, 0x0f, 0xb6, 0x03, 0xf7, 0x68, 0xde, 0xfe, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0x50, 0xc1, 0x00, 0x2f, 0xa1, 0x03, 0x00, 0x00,
}
